name: BuildAppPinnings

on:
  push:
    branches:
      - main
    paths:
      - "apin/**"
jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Git branch name
      id: git-branch-name
      uses: EthanSK/git-branch-name-action@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Install pack cli
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli -yy
          sudo apt-get update -yy
          sudo apt-get install pack-cli -yy

    - name: Build and push container image to registry
        run: |
          pack build --path ./github-actions --builder paketobuildpacks/builder:base --publish ${{ secrets.AWS_ECR_URL }}/infra-test:apin-{{ github.sha }}    --cache-image   ${{ secrets.AWS_ECR_ROOT }}/infra-test:cache-apin-{{ github.sha }} 
