#this application points to the mother module
#git@github.com:mr-saoirse/app.pinnings.git
#https://github.com/mr-saoirse/app.pinnings/tree/main/stack/modules/mother-deployment

#see:https://argo-cd.readthedocs.io/en/stable/user-guide/helm/
#kubectl apply -f application-sets/core/mother-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mother-app
spec:
  project: default
  source:
    chart: mother-deployment
    repoURL: https://github.com/mr-saoirse/app.pinnings/tree/main/stack/modules
    #set this to our origin revision - custom module
    targetRevision: 0.1.0
    helm:
      valuesObject:
        image:
          repository: 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test
          tag: apin-latest
  destination:
    namespace: argo
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
