apiVersion: v1
kind: Pod
metadata:
  labels:
    app: apin-scheduler-test
    app.kubernetes.io/instance: mother-app
  name: apin-scheduler-test
  namespace: argo
spec:
  containers:
    - image: "286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:apin-latest"
      command: ["poetry", "run", "apin", "scheduler", "start"]
      imagePullPolicy: Always
      name: apin-scheduler
      resources:
        limits:
          cpu: "0.2"
          memory: 128Mi
        requests:
          cpu: "0.1"
          memory: 64Mi
