 
# templates/scheduler.yaml
apiVersion: v1
kind: Pod
metadata:
  name: apin-scheduler
spec:
  containers:
  - name: apin-scheduler
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    command: ["apin", "scheduler", "start"]
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"