 
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name:  "todo-attribute-name"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name:  "todo-attribute-name"
    app.kubernetes.io/instance: {{ .Release.Name }}