name: BuildAppPinnings

on:
  push:
    branches:
      - main
    paths:
      - "apin/**"
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Git branch name
        id: git-branch-name
        uses: EthanSK/git-branch-name-action@v1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install pack cli
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli -yy
          sudo apt-get update -yy
          sudo apt-get install pack-cli -yy

      - name: Build and push container image to registry
        run: |
          pack build --builder paketobuildpacks/builder:base --publish 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:apin-${{ github.sha }}    --cache-image   286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:cache-apin-${{ github.sha }}

      #pack build --builder paketobuildpacks/builder:base --publish 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:apin-latest    --cache-image   286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:cache-apin-latest
      #pack config trusted-builders list [flags] <- try the heroku one
      #pack build --builder paketobuildpacks/builder:base --publish 286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:apin-${{ github.sha }}    --cache-image   286292902993.dkr.ecr.us-east-1.amazonaws.com/infra-test:cache-apin-${{ github.sha }}

      #get the changes and post them
      # - uses: jitterbit/get-changed-files@v1
      #   id: detect_changes
      #   continue-on-error: true
      #   with:
      #     format: csv
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Post Changes
      #   run: |
      #     python .github/workflows/post_changes.py ${{ secrets.APIN_KEY }} ${{ github.sha }} ${{ steps.detect_changes.outputs.all }}
